export const COUNTRIES_DATA = [
    {
        code: "US",
        name: "United States",
        flag: "/images/flags/usa.png",
        govFee: 160,
        touristVisa: 50,
        businessVisa: 75,
        serviceFee: 30,
        tourGroupSupport: "24/7 support for your visa application process.",
    },
    {
        code: "CA",
        name: "Canada",
        flag: "/images/flags/canada.png",
        govFee: 100,
        touristVisa: 40,
        businessVisa: 60,
        serviceFee: 25,
        tourGroupSupport: "Expert assistance for Canadian visa applications.",
    },
    {
        code: "GB",
        name: "United Kingdom",
        flag: "/images/flags/united-kingdom.png",
        govFee: 95,
        touristVisa: 30,
        businessVisa: 50,
        serviceFee: 20,
        tourGroupSupport: "Comprehensive support for UK visa applications.",
    },
    {
        code: "AU",
        name: "Australia",
        flag: "/images/flags/australia.png",
        govFee: 140,
        touristVisa: 45,
        businessVisa: 70,
        serviceFee: 35,
        tourGroupSupport: "Dedicated support for Australian visa applications.",
    },
    {
        code: "IN",
        name: "India",
        flag: "/images/flags/india.png",
        govFee: 2000,
        touristVisa: 500,
        businessVisa: 1000,
        serviceFee: 300,
        tourGroupSupport: "24/7 support for Indian visa applications.",
    },
    {
        code: "JP",
        name: "Japan",
        flag: "/images/flags/japan.png",
        govFee: 15,
        touristVisa: 20,
        businessVisa: 15,
        serviceFee: 20,
        tourGroupSupport: "Expert assistance for Japanese visa applications.",
    },
    {
        code: "FR",
        name: "France",
        flag: "/images/flags/france.png",
        govFee: 80,
        touristVisa: 30,
        businessVisa: 50,
        serviceFee: 20,
        tourGroupSupport: "Comprehensive support for French visa applications.",
    },
    {
        code: "DE",
        name: "Germany",
        flag: "/images/flags/de.png",
        govFee: 75,
        touristVisa: 25,
        businessVisa: 40,
        serviceFee: 15,
        tourGroupSupport: "Dedicated support for German visa applications.",
    },
    {
        code: "IT",
        name: "Italy",
        flag: "/images/flags/it.png",
        govFee: 70,
        touristVisa: 20,
        businessVisa: 35,
        serviceFee: 15,
        tourGroupSupport: "24/7 support for Italian visa applications.",
    },
    {
        code: "ES",
        name: "Spain",
        flag: "/images/flags/es.png",
        govFee: 60,
        touristVisa: 15,
        businessVisa: 30,
        serviceFee: 10,
        tourGroupSupport: "Expert assistance for Spanish visa applications.",
    },
];

export const SERVICE_FEE = 59.99;
